* More fixed to experiment retry feature

diff --git a/bin/freja b/bin/freja
--- a/bin/freja
+++ b/bin/freja
@@ -734,8 +734,8 @@ batch()
 			done | cut -f 1 -d :|tr \\\n ' '|xargs echo`"
 			info_stop done.
 		fi
-	else
-		retry_expr=/bin/true
+	#else
+		#retry_expr=#/bin/true
 	fi
 
 	if [ "$retry_only" != "1" ] || [ "count_selected_only" == "0" ]
@@ -816,7 +816,15 @@ batch()
 			## Only run this experiment if there is no output for this one
 			#if [ -f $output_dir/${basename}_$output_success$output_extension ] && [ "`echo $retry_numbers|tr \\\t ' '|tr -s ' '|xargs echo|tr ' ' \\\n|grep ^$(($instance_number + filtered_counter))$`" == "" ]
 			eval line=\"$flags $args\"
-			eval 'if [ -f $output_dir/${basename}_$output_success$output_extension ] || ! (' $retry_expr ' )
+
+			if [ "$retry_expr" == "" ]
+			then
+				retry_expr_dummy=/bin/true
+			else
+				retry_expr_dummy="$retry_expr"
+			fi
+
+			eval 'if ( [ -f $output_dir/${basename}_$output_success$output_extension ] && [ "$retry_numbers" == "" ] && [ "$retry_expr" == "" ] ) || ( [ "$retry_numbers" != "" ] && [ "`echo $retry_numbers|tr \\\t " "|tr -s " "|xargs echo|tr " " \\\n|grep ^$(($instance_number + filtered_counter))$`" == "" ] ) || ( [ "$retry_expr" != "" ] && ! ( $retry_expr_dummy ) )
 			then
 				local outcome="Skipped"
 				local skipped=$(($skipped + 1))
@@ -1044,7 +1052,7 @@ parse_options()
 						retry_numbers="$1"
 					;;
 					"--all" | "-a")
-						retry_expr='/bin/true' ## An expression that returns true for all experiments
+						retry_expr='/bin/true' ## An expression that returns true for all experiments.
 					;;
 					"")
 						## If an empty parameter for the filtering method manages to reach here,
